# Generated by Django 6.0.4 on 2026-04-18 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('rendez_vous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationDjomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_api', models.CharField(help_text='Lue depuis .env — ne pas stocker en clair en production', max_length=255, verbose_name='Clé API')),
                ('url_base', models.CharField(default='https://api.djomy.africa/v1', max_length=255, verbose_name='URL de base')),
                ('url_webhook', models.CharField(blank=True, help_text='URL de retour pour les webhooks Djomy', max_length=255, verbose_name='URL webhook')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Configuration Djomy',
                'verbose_name_plural': 'Configurations Djomy',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_interne', models.CharField(max_length=30, unique=True, verbose_name='Référence interne')),
                ('reference_djomy', models.CharField(blank=True, help_text='ID de transaction retourné par Djomy', max_length=100, verbose_name='Référence Djomy')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('devise', models.CharField(default='GNF', max_length=5, verbose_name='Devise')),
                ('mode_paiement', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('wave', 'Wave'), ('carte_bancaire', 'Carte bancaire'), ('especes', 'Espèces')], default='orange_money', max_length=20, verbose_name='Mode de paiement')),
                ('statut_paiement', models.CharField(choices=[('en_attente', 'En attente'), ('initie', 'Initié'), ('confirme', 'Confirmé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('webhook_payload', models.JSONField(blank=True, help_text='Payload brut reçu du webhook Djomy', null=True, verbose_name='Payload webhook')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='consultations.consultation', verbose_name='Consultation')),
                ('rendez_vous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement', to='rendez_vous.rendezvous', verbose_name='Rendez-vous')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['statut_paiement'], name='paiements_p_statut__f2db99_idx'), models.Index(fields=['reference_djomy'], name='paiements_p_referen_9143b8_idx')],
            },
        ),
    ]
