# Generated by Django 6.0.4 on 2026-04-18 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disponibilites', '0001_initial'),
        ('medecins', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateField(verbose_name='Date du rendez-vous')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('statut_rdv', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule_patient', 'Annulé par le patient'), ('annule_medecin', 'Annulé par le médecin'), ('termine', 'Terminé'), ('no_show', 'Non présenté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('motif', models.TextField(blank=True, verbose_name='Motif de la consultation')),
                ('canal', models.CharField(choices=[('plateforme', 'Plateforme'), ('telephone', 'Téléphone'), ('direct', 'Direct')], default='plateforme', max_length=15, verbose_name='Canal de prise de rendez-vous')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('disponibilite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='disponibilites.disponibilite', verbose_name='Créneau')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='medecins.medecin', verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_rdv', '-heure_debut'],
                'indexes': [models.Index(fields=['medecin', 'date_rdv', 'statut_rdv'], name='rendez_vous_medecin_763ed4_idx'), models.Index(fields=['patient', 'date_rdv'], name='rendez_vous_patient_c8cac9_idx')],
            },
        ),
    ]
