# Generated by Django 6.0.4 on 2026-04-18 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecins', '0001_initial'),
        ('patients', '0001_initial'),
        ('rendez_vous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(max_length=20, unique=True, verbose_name='Numéro de dossier')),
                ('date_ouverture', models.DateField(auto_now_add=True, verbose_name="Date d'ouverture")),
                ('statut_dossier', models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé'), ('suspendu', 'Suspendu')], default='actif', max_length=10, verbose_name='Statut')),
                ('notes_generales', models.TextField(blank=True, verbose_name='Notes générales')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Dossier médical',
                'verbose_name_plural': 'Dossiers médicaux',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(verbose_name='Date et heure de la consultation')),
                ('compte_rendu', models.TextField(blank=True, verbose_name='Compte rendu')),
                ('diagnostic', models.TextField(blank=True, verbose_name='Diagnostic')),
                ('prescription', models.TextField(blank=True, verbose_name='Prescription')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='medecins.medecin', verbose_name='Médecin')),
                ('rendez_vous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='rendez_vous.rendezvous', verbose_name='Rendez-vous')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='consultations.dossiermedical', verbose_name='Dossier médical')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date_consultation'],
            },
        ),
    ]
