# Generated by Django 6.0.5 on 2026-06-12 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ordonnance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Numéro d'ordonnance"
                    ),
                ),
                (
                    "token_verification",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Encodé dans le QR code pour vérifier l'authenticité",
                        unique=True,
                        verbose_name="Jeton de vérification",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Recommandations au patient (repos, régime, suivi…)",
                        verbose_name="Instructions générales",
                    ),
                ),
                (
                    "date_emission",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'émission"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "consultation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordonnance",
                        to="consultations.consultation",
                        verbose_name="Consultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordonnance",
                "verbose_name_plural": "Ordonnances",
                "ordering": ["-date_emission"],
            },
        ),
        migrations.CreateModel(
            name="LigneOrdonnance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicament",
                    models.CharField(max_length=150, verbose_name="Médicament"),
                ),
                (
                    "posologie",
                    models.CharField(
                        help_text="Ex : 1 comprimé matin et soir",
                        max_length=150,
                        verbose_name="Posologie",
                    ),
                ),
                (
                    "duree",
                    models.CharField(
                        blank=True,
                        help_text="Ex : 7 jours",
                        max_length=100,
                        verbose_name="Durée",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
                ),
                (
                    "ordonnance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="consultations.ordonnance",
                        verbose_name="Ordonnance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'ordonnance",
                "verbose_name_plural": "Lignes d'ordonnance",
                "ordering": ["ordre", "id"],
            },
        ),
    ]
