# Generated by Django 6.0.4 on 2026-04-18 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_disponibilite', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('statut_creneau', models.CharField(choices=[('libre', 'Libre'), ('reserve', 'Réservé'), ('indisponible', 'Indisponible'), ('annule', 'Annulé')], default='libre', max_length=15, verbose_name='Statut du créneau')),
                ('type_creneau', models.CharField(choices=[('presentiel', 'Présentiel'), ('teleconsultation', 'Téléconsultation'), ('les_deux', 'Présentiel & Téléconsultation')], default='presentiel', max_length=20, verbose_name='Type de créneau')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='medecins.medecin', verbose_name='Médecin')),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
                'ordering': ['date_disponibilite', 'heure_debut'],
                'indexes': [models.Index(fields=['medecin', 'date_disponibilite', 'statut_creneau'], name='disponibili_medecin_0f1c8a_idx')],
            },
        ),
    ]
