# Generated by Django 6.0.4 on 2026-04-18 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, help_text='Ex : bi-heart-pulse', max_length=50, verbose_name='Icône Bootstrap')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'ordre")),
                ('biographie', models.TextField(blank=True, verbose_name='Biographie')),
                ('tarif_consultation', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarif consultation')),
                ('mode_exercice', models.CharField(choices=[('liberal', 'Libéral'), ('salarie', 'Salarié'), ('mixte', 'Mixte')], default='liberal', max_length=10, verbose_name="Mode d'exercice")),
                ('accepte_nouveaux_patients', models.BooleanField(default=True, verbose_name='Accepte de nouveaux patients')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('specialites', models.ManyToManyField(blank=True, related_name='medecins', to='medecins.specialite', verbose_name='Spécialités')),
            ],
            options={
                'verbose_name': 'Médecin',
                'verbose_name_plural': 'Médecins',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
