# Generated by Django 6.0.4 on 2026-04-18 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rendez_vous', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('confirmation_rdv', 'Confirmation de rendez-vous'), ('rappel_rdv', 'Rappel de rendez-vous'), ('annulation_rdv', 'Annulation de rendez-vous'), ('modification_rdv', 'Modification de rendez-vous'), ('paiement_confirme', 'Paiement confirmé'), ('paiement_echoue', 'Paiement échoué'), ('info_generale', 'Information générale')], max_length=25, verbose_name='Type')),
                ('canal', models.CharField(choices=[('application', 'Application'), ('email', 'Email'), ('sms', 'SMS')], default='application', max_length=15, verbose_name='Canal')),
                ('contenu_resume', models.TextField(verbose_name='Contenu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('statut_notification', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('lu', 'Lu'), ('echoue', 'Échoué')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='rendez_vous.rendezvous', verbose_name='Rendez-vous')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_envoi'],
                'indexes': [models.Index(fields=['utilisateur', 'statut_notification'], name='notificatio_utilisa_b85413_idx'), models.Index(fields=['date_envoi'], name='notificatio_date_en_1a8f7a_idx')],
            },
        ),
    ]
